name: iOS Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby for Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build and archive app
        run: |
          xcodebuild -workspace FaisalGame.xcworkspace -scheme FaisalGame -sdk iphoneos -configuration Release archive -archivePath $PWD/build/FaisalGame.xcarchive
          xcodebuild -exportArchive -archivePath $PWD/build/FaisalGame.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath $PWD/build

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: FaisalGame.ipa
          path: build/FaisalGame.ipa
